jwt:
  secret: s0e1c2r3e4t5
  lifetime: 30m

# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      # http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    # http://www.h2database.com/html/features.html#in_memory_databases
    # http://www.h2database.com/html/features.html#compatibility
    url: jdbc:h2:mem:jwt;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    # tcp: jdbc:h2:tcp://localhost:9092/mem:jwt - access from intellij idea
    username: sa
    password:

logging:
  level:
    root: WARN
    com.example.jwt: INFO
    org.springframework.security.web.SecurityFilterChain: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true